name: Main Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: ["*"] # Run CI on all pushes

jobs:
  build:
    name: Run CI
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Run CD

    needs: build

    # Only run on a push to the 'main' branch
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    uses: ./.github/workflows/cd.yml

    secrets: inherit
